### PR TITLE
fix endpoint:'/api/' issue #112

### PR DESCRIPTION
**Pull request by GammaNu**
the coverage still 100% but the feature can be reversed without the if and no test fail :/
Feel free to add a unit test on it ;)

### CODE REVIEW

**Comment by Marsup** [comment]
I don't think that's a correct solution for your problem. I've added more checks for your error, can you try the current master branch ?

**Comment by GammaNu** [comment]
it works with your current master :)
Could you push it on npm ?

**Comment by gergoerdosi** [comment]
@GammaNu Your proposed changes look quite complicated. Can't we just remove the trailing slash from `settings.endpoint`?

```js
var cssBaseUrl = settings.endpoint.replace(/\/+$/, '') + '/css';
```

**Comment by Marsup** [comment]
Can you be more explicit on what works and what doesn't, what are the symptoms ?

**Pull request closed without merging**
