### PR TITLE
Fixes two issues #161 and #162

### PR DESCRIPTION
**Pull request by danactive**
* Fix hyperlink to hapi guidelines for contributing (#161)
* Blankie support whitelists CDN fonts, styles, and scripts (#162)

* Tested on Windows (no additional tests fail)
* Optionally compatible with [blankie](https://github.com/nlf/blankie) closes blankie issue (https://github.com/nlf/blankie/issues/15)
  * Works with or without blankie

### CODE REVIEW

**Comment by danactive** [comment]
Anyone able to help with this test failure? It's not clear what the string test is expecting.

**Comment by Marsup** [comment]
I'll have a look at the test failure, it's unrelated to this PR. I'd prefer an extension point rather than a hard-coded blankie config in there.

**Comment by danactive** [comment]
@Marsup Are you referring to an extension point such as onPreStart? I'm not able to change or define the route information on that server event.

**Comment by Marsup** [comment]
I mean be able to provide those options as part of the initialization of the plugin, this way it would support more than this specific use case.

**Comment by Marsup** [comment]
Do you still want to push this ?

**Comment by danactive** [comment]
Nah, it doesn't fit the project expectations

**Pull request closed without merging**
