### PR TITLE
initial stab at rendering cors

### PR DESCRIPTION
**Pull request by wraithgar**
This is an attempt to address https://github.com/hapijs/lout/issues/102. It does seem like overkill, so some further direction could help to make this a better PR.

### CODE REVIEW

**Comment by Marsup** [comment]
The object is quite flat, so having a dd/dt pair like we did on others makes the most sense.
Booleans should render just fine naturally, the arrays might be either a comma separated list, or an ul/li list, I think the latest brings the more flexibility for styling.

**Comment by wraithgar** [comment]
Here's a second attempt. I omitted the internal `_` keys that HAPI adds and stuck to the ones defined in the docs.

**Comment by Marsup** [comment]
This will probably fail if cors is a simple true boolean.

**Comment by wraithgar** [comment]
If cors is set to true, then all the defaults are applied. I can add a cors: true test to this just to make sure though if you want.

**Comment by Marsup** [comment]
Oh, hapi making its magic then. Yes an additional test would be great.

**Comment by wraithgar** [comment]
Ok we're testing that cors shows up, and has one of the default properties properly rendered if we have `cors: true` on a route.

**Comment by Marsup** [comment]
I guess nothing would appear if it were false ?

**Comment by wraithgar** [comment]
Yes, thanks. I added an assertion to the default route template to make sure of this.

**Comment by Marsup** [comment]
Great, can you squash all your commits ?

**Comment by wraithgar** [comment]
Squished, force pushed, not sure if that was the right way to do it but here we are.

**Pull request merged**
